set -g automatic-rename on
__DECK_AUTOMATIC_RENAME_FORMAT__set -g history-limit __DECK_HISTORY_LIMIT__
set -g destroy-unattached off
set -g status off
set -g prefix None
set -g prefix2 None
unbind -a -T prefix
unbind -a -T root
set -g @resurrect-dir '__DECK_RESURRECT_DIR__'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes ':all:'
run-shell '__DECK_RESURRECT_PLUGIN__'
