set -g automatic-rename on
set -g history-limit 50000
set -g destroy-unattached off
set -g status off
set -g prefix None
set -g prefix2 None
unbind -a -T prefix
unbind -a -T root
set -g set-titles on
set -g set-titles-string "#{pane_current_command}"
