import { dirname, join } from 'node:path';
import type { AgentName } from './agentTypes';

export function renderAgentHookScript(
  sidecarDir: string,
  agent: AgentName = 'claude',
  statusDir = join(dirname(sidecarDir), 'status'),
): string {
  return [
    '#!/bin/sh',
    'set -eu',
    '',
    `agent="\${2:-${agent}}"`,
    'case "$agent" in',
    '  claude|codex) ;;',
    '  *) exit 0 ;;',
    'esac',
    '',
    'payload=$(cat)',
    'if [ -z "${DECK_SESSION:-}" ]; then',
    '  exit 0',
    'fi',
    '',
    `status_dir='${quoteForSingleQuotedShell(statusDir)}'`,
    'hook_event_name=$(printf "%s" "$payload" | sed -n \'s/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p\')',
    'if [ "$hook_event_name" = "SessionEnd" ]; then',
    '  rm -f "$status_dir/$DECK_SESSION.json" || true',
    '  tmux -L deck set -w -t "$DECK_SESSION" automatic-rename on || true',
    '  exit 0',
    'fi',
    '',
    'session_id=$(printf "%s" "$payload" | sed -n \'s/.*"session_id"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p\')',
    'if [ -z "$session_id" ]; then',
    '  exit 0',
    'fi',
    '',
    `sidecar_dir='${quoteForSingleQuotedShell(sidecarDir)}'`,
    'mkdir -p "$sidecar_dir"',
    'printf \'{"agent":"%s","session_id":"%s"}\\n\' "$agent" "$session_id" > "$sidecar_dir/$DECK_SESSION.json"',
    '',
    'notification_type=$(printf "%s" "$payload" | sed -n \'s/.*"notification_type"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p\')',
    'message=$(printf "%s" "$payload" | sed -n \'s/.*"message"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p\')',
    'json_escape() {',
    '  printf "%s" "$1" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g\'',
    '}',
    'write_status() {',
    '  mkdir -p "$status_dir" || return 0',
    '  tmp=$(mktemp "$status_dir/$DECK_SESSION.XXXXXX") || return 0',
    '  status_at=$(date +%s 2>/dev/null || printf 0)',
    '  if [ "$#" -gt 1 ]; then',
    '    escaped_message=$(json_escape "$2") || { rm -f "$tmp"; return 0; }',
    '    printf \'{"status":"%s","statusAt":%s,"message":"%s"}\\n\' "$1" "$status_at" "$escaped_message" > "$tmp" || { rm -f "$tmp"; return 0; }',
    '  else',
    '    printf \'{"status":"%s","statusAt":%s}\\n\' "$1" "$status_at" > "$tmp" || { rm -f "$tmp"; return 0; }',
    '  fi',
    '  mv "$tmp" "$status_dir/$DECK_SESSION.json" || { rm -f "$tmp"; return 0; }',
    '}',
    '',
    // Rename last: the sidecar write above is what AgentSession resume depends on,
    // so a naming failure (or a future event missing hook_event_name) must never
    // pre-empt it.
    'case "$hook_event_name" in',
    '  SessionStart) tmux -L deck rename-window -t "$DECK_SESSION" "$agent" || true ;;',
    '  UserPromptSubmit) write_status inProgress || true; tmux -L deck rename-window -t "$DECK_SESSION" "$agent" || true ;;',
    '  PreToolUse|PostToolUse|PostToolUseFailure) write_status inProgress || true ;;',
    '  PermissionRequest) write_status needsInput "$message" || true ;;',
    '  Stop) write_status completed || true ;;',
    '  StopFailure) write_status failed || true ;;',
    '  Notification)',
    '    case "$notification_type" in',
    '      permission_prompt|elicitation_dialog) write_status needsInput "$message" || true ;;',
    '      idle_prompt) write_status completed || true ;;',
    '    esac',
    '    ;;',
    'esac',
    '',
  ].join('\n');
}

function quoteForSingleQuotedShell(value: string): string {
  return value.replaceAll("'", "'\"'\"'");
}
