import { dirname, join } from 'node:path';
import type { AgentName } from './agentTypes';

export function renderAgentHookScript(
  sidecarDir: string,
  agent: AgentName = 'claude',
  statusDir = join(dirname(sidecarDir), 'status'),
): string {
  return [
    '#!/bin/sh',
    'set -eu',
    // Deck only observes. A Codex PermissionRequest hook that exits 2 is read as
    // Deny (any non-zero marks it Failed), so force exit 0 on every path — even a
    // stray set -e abort — and a hook can never deny a prompt (ADR-0026 §4).
    "trap 'exit 0' EXIT",
    '',
    `agent="\${2:-${agent}}"`,
    'case "$agent" in',
    '  claude|codex) ;;',
    '  *) exit 0 ;;',
    'esac',
    '',
    'payload=$(cat)',
    'if [ -z "${DECK_SESSION:-}" ]; then',
    '  exit 0',
    'fi',
    '',
    // First-occurrence, escape-aware JSON string extraction. sed-style
    // last-occurrence matching let nested tool_input text shadow top-level
    // fields, and [^"]* truncated values at the first escaped quote. Top-level
    // keys precede tool_input in hook payloads, so first occurrence (skipping
    // \"-escaped key lookalikes) selects the real field.
    'json_field() {',
    '  printf "%s" "$payload" | awk -v key="$1" \'',
    '    { buf = buf $0 "\\n" }',
    '    END {',
    '      k = "\\"" key "\\""',
    '      off = 1; pos = 0',
    '      while ((p = index(substr(buf, off), k)) > 0) {',
    '        p = off + p - 1',
    '        prev = p > 1 ? substr(buf, p - 1, 1) : ""',
    '        rest = substr(buf, p + length(k))',
    '        if (prev != "\\\\" && rest ~ /^[[:space:]]*:/) { pos = p; break }',
    '        off = p + 1',
    '      }',
    '      if (pos == 0) exit',
    '      s = substr(buf, pos + length(k))',
    '      sub(/^[[:space:]]*:[[:space:]]*/, "", s)',
    '      if (substr(s, 1, 1) != "\\"") exit',
    '      s = substr(s, 2)',
    '      out = ""',
    '      while (1) {',
    '        match(s, /^[^"\\\\]*/)',
    '        if (RLENGTH > 0) { out = out substr(s, 1, RLENGTH); s = substr(s, RLENGTH + 1) }',
    '        if (substr(s, 1, 1) != "\\\\") break',
    '        e = substr(s, 2, 1)',
    '        if (e == "n" || e == "t") { out = out " " } else { out = out e }',
    '        s = substr(s, 3)',
    '      }',
    '      print out',
    '    }\'',
    '}',
    '',
    `status_dir='${quoteForSingleQuotedShell(statusDir)}'`,
    `sidecar_dir='${quoteForSingleQuotedShell(sidecarDir)}'`,
    'agent_pid=$PPID',
    'agent_start_time=$(ps -o lstart= -p "$agent_pid" 2>/dev/null | awk \'{$1=$1; print}\' || true)',
    'hook_event_name=$(json_field hook_event_name)',
    'session_id=$(json_field session_id)',
    'if [ -z "$session_id" ]; then',
    '  exit 0',
    'fi',
    '',
    'notification_type=$(json_field notification_type)',
    'message=$(json_field message)',
    'json_escape() {',
    '  printf "%s" "$1" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g\'',
    '}',
    'write_sidecar() {',
    '  mkdir -p "$sidecar_dir" || return 0',
    '  tmp=$(mktemp "$sidecar_dir/$DECK_SESSION.XXXXXX") || return 0',
    '  escaped_start_time=$(json_escape "$agent_start_time") || { rm -f "$tmp"; return 0; }',
    '  printf \'{"agent":"%s","session_id":"%s","pid":%s,"startTime":"%s"}\\n\' "$agent" "$session_id" "$agent_pid" "$escaped_start_time" > "$tmp" || { rm -f "$tmp"; return 0; }',
    '  mv "$tmp" "$sidecar_dir/$DECK_SESSION.json" || { rm -f "$tmp"; return 0; }',
    '}',
    'write_status_json() {',
    '  mkdir -p "$status_dir" || return 0',
    '  tmp=$(mktemp "$status_dir/$DECK_SESSION.XXXXXX") || return 0',
    '  status_at=$(date +%s 2>/dev/null || printf 0)',
    '  if [ "$#" -gt 1 ]; then',
    '    escaped_message=$(json_escape "$2") || { rm -f "$tmp"; return 0; }',
    '    printf \'{"status":"%s","statusAt":%s,"agent":"%s","message":"%s"}\\n\' "$1" "$status_at" "$agent" "$escaped_message" > "$tmp" || { rm -f "$tmp"; return 0; }',
    '  else',
    '    printf \'{"status":"%s","statusAt":%s,"agent":"%s"}\\n\' "$1" "$status_at" "$agent" > "$tmp" || { rm -f "$tmp"; return 0; }',
    '  fi',
    '  mv "$tmp" "$status_dir/$DECK_SESSION.json" || { rm -f "$tmp"; return 0; }',
    '}',
    'write_status() {',
    '  write_status_json "$1"',
    '}',
    'write_status_with_message() {',
    '  write_status_json "$1" "$2"',
    '}',
    'write_status_maybe_message() {',
    '  if [ "$#" -gt 1 ] && [ -n "$2" ]; then',
    '    write_status_with_message "$1" "$2"',
    '  else',
    '    write_status "$1"',
    '  fi',
    '}',
    '',
    // Rename last: the identity sidecar write is what AgentSession resume depends on,
    // so a naming failure must never pre-empt it.
    'case "$hook_event_name" in',
    '  SessionStart) write_sidecar || true; tmux -L deck rename-window -t "$DECK_SESSION" "$agent" || true ;;',
    '  UserPromptSubmit) write_sidecar || true; write_status inProgress || true; tmux -L deck rename-window -t "$DECK_SESSION" "$agent" || true ;;',
    '  PreToolUse) write_status inProgress || true ;;',
    '  PostToolUse|PostToolUseFailure) [ "$agent" = "claude" ] && write_status inProgress || true ;;',
    '  PermissionRequest)',
    '    if [ "$agent" = "codex" ]; then write_status_with_message needsInput "" || true; else write_status_maybe_message needsInput "$message" || true; fi',
    '    ;;',
    '  Stop) write_status completed || true ;;',
    '  StopFailure) [ "$agent" = "claude" ] && write_status failed || true ;;',
    '  Notification)',
    '    [ "$agent" = "claude" ] || exit 0',
    '    case "$notification_type" in',
    '      permission_prompt|elicitation_dialog) write_status_maybe_message needsInput "$message" || true ;;',
    // idle_prompt confirms an existing completion (it trails Stop by ~a minute);
    // minting a fresh statusAt here would re-arm unread on turns already read.
    '      idle_prompt) grep -q \'"status":"completed"\' "$status_dir/$DECK_SESSION.json" 2>/dev/null || write_status completed || true ;;',
    '    esac',
    '    ;;',
    'esac',
    '',
  ].join('\n');
}

function quoteForSingleQuotedShell(value: string): string {
  return value.replaceAll("'", "'\"'\"'");
}
